# Generated by Django 4.1.13 on 2025-03-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(default=5),
        ),
    ]
