# Generated by Django 4.1.13 on 2025-04-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_exam_duration_disqualifiedattempt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disqualifiedattempt',
            unique_together={('user', 'exam')},
        ),
    ]
