# Generated by Django 4.1.13 on 2025-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_disqualifiedattempt_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='status',
            field=models.CharField(choices=[('Attempted', 'Attempted'), ('Disqualified', 'Disqualified')], default='Attempted', max_length=20),
        ),
    ]
